version: 2
jobs:
  build-and-test:
    docker:
    - image: circleci/python:latest
    steps:
    - checkout
    - restore_cache:
        keys:
        - pip-{{ checksum "pollsapi/requirements.txt"  }}
    - run:
        command: |
          if true; then
            pip install --user -r pollsapi/requirements.txt
          else
            pip install -r pollsapi/requirements.txt
          fi
        name: Install Dependencies
    - save_cache:
        key: pip-{{ checksum "requirements.txt"  }}
        paths:
        - /home/circleci/.local/lib/
    - run:
        command: ./manage.py test
        name: Test
workflows:
  main:
    jobs:
    - build-and-test